"""Tests for review responder routes."""

from datetime import UTC, datetime

from fastapi.testclient import TestClient
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.models.credits import UsageRecord
from app.models.notification import NotificationDeliveryLog, NotificationEvent
from app.models.oauth import OAuthProvider, OAuthStatus, OAuthToken
from app.models.review_response import BulkRetryLog, ResponseStatus, ReviewIntent, ReviewResponse


def _naive_utc_now() -> datetime:
    return datetime.now(UTC).replace(tzinfo=None)


def _usage_total(db: Session, account_id, usage_type: str) -> int:
    return int(
        db.query(func.coalesce(func.sum(UsageRecord.monthly_count), 0))
        .filter(UsageRecord.account_id == account_id, UsageRecord.usage_type == usage_type)
        .scalar()
        or 0
    )


class TestReviewResponderGeneration:
    """Tests for review response generation usage honesty."""

    def test_generate_response_records_usage_only_on_real_ai_success(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Successful AI draft generation should consume one review_responses usage."""

        async def fake_generate(_self, prompt: str) -> str:
            if "Analyze the following customer review" in prompt:
                return (
                    '{"sentiment_score": 0.9, "sentiment_label": "positive", '
                    '"intent": "praise", "detected_issues": [], "key_phrases": ["great service"]}'
                )
            return "Thank you for the kind words!\n\nGenerated by AI - Subject to human review"

        monkeypatch.setattr("app.integrations.llm.LLMAdapter.generate", fake_generate)
        monkeypatch.setattr("app.routers.review_responder.check_rate_limit", _allow_rate_limit)

        response = client.post(
            "/reviews/generate-response",
            headers=auth_headers,
            json={
                "location_id": str(test_location.id),
                "review_id": "review-generate-success",
                "review_author": "Happy Customer",
                "review_rating": 5,
                "review_text": "Great service and friendly staff.",
            },
        )

        assert response.status_code == 200
        assert "Thank you for the kind words!" in response.json()["draft_text"]
        assert _usage_total(db, test_location.account_id, "review_responses") == 1

    def test_generate_response_fallback_does_not_record_usage(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Fallback draft generation should stay honest and not consume usage."""

        async def fake_generate(_self, prompt: str) -> str:
            if "Analyze the following customer review" in prompt:
                return (
                    '{"sentiment_score": -0.7, "sentiment_label": "negative", '
                    '"intent": "complaint", "detected_issues": ["slow service"], '
                    '"key_phrases": ["slow service"]}'
                )
            raise RuntimeError("provider unavailable")

        monkeypatch.setattr("app.integrations.llm.LLMAdapter.generate", fake_generate)
        monkeypatch.setattr("app.routers.review_responder.check_rate_limit", _allow_rate_limit)

        response = client.post(
            "/reviews/generate-response",
            headers=auth_headers,
            json={
                "location_id": str(test_location.id),
                "review_id": "review-generate-fallback",
                "review_author": "Unhappy Customer",
                "review_rating": 2,
                "review_text": "Service was too slow.",
            },
        )

        assert response.status_code == 200
        assert "Please contact us directly" in response.json()["draft_text"]
        assert _usage_total(db, test_location.account_id, "review_responses") == 0

    def test_create_response_fallback_does_not_record_usage(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Persisting a fallback draft should not consume review_responses usage."""

        async def fake_generate(_self, _prompt: str) -> str:
            raise RuntimeError("provider unavailable")

        async def fake_send_notification(self, *args, **kwargs):
            return {"success": True}

        monkeypatch.setattr("app.integrations.llm.LLMAdapter.generate", fake_generate)
        monkeypatch.setattr(
            "app.services.notification.NotificationService.send_notification",
            fake_send_notification,
        )
        monkeypatch.setattr("app.routers.review_responder.check_rate_limit", _allow_rate_limit)

        response = client.post(
            "/reviews/create-response",
            headers=auth_headers,
            json={
                "location_id": str(test_location.id),
                "review_id": "review-create-fallback",
                "review_author": "Needs Support",
                "review_rating": 1,
                "review_text": "Nobody called me back.",
            },
        )

        assert response.status_code == 200
        assert response.json()["review_id"] == "review-create-fallback"
        assert _usage_total(db, test_location.account_id, "review_responses") == 0

    def test_create_response_existing_record_does_not_record_additional_usage(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Returning an existing review response should not consume usage again."""

        existing = ReviewResponse(
            location_id=test_location.id,
            review_id="review-existing-no-charge",
            review_author="Customer",
            review_rating=5,
            review_text="Great experience",
            review_date=_naive_utc_now(),
            ai_draft="Thanks for the review!",
            intent=ReviewIntent.PRAISE,
            tone="grateful",
            status=ResponseStatus.PENDING,
        )
        db.add(existing)
        db.commit()

        async def fail_if_called(_self, _prompt: str) -> str:
            raise AssertionError("LLM should not be called for an existing response")

        monkeypatch.setattr("app.integrations.llm.LLMAdapter.generate", fail_if_called)
        monkeypatch.setattr("app.routers.review_responder.check_rate_limit", _allow_rate_limit)

        response = client.post(
            "/reviews/create-response",
            headers=auth_headers,
            json={
                "location_id": str(test_location.id),
                "review_id": "review-existing-no-charge",
                "review_author": "Customer",
                "review_rating": 5,
                "review_text": "Great experience",
            },
        )

        assert response.status_code == 200
        assert response.json()["id"] == existing.id
        assert _usage_total(db, test_location.account_id, "review_responses") == 0


async def _allow_rate_limit(*args, **kwargs) -> None:
    return None


class TestReviewResponderPending:
    """Tests for pending review response listing."""

    def test_pending_responses_hides_other_accounts_location(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        other_location,
    ) -> None:
        """Another account's location filter should return 404."""
        response = client.get(
            f"/reviews/pending?location_id={other_location.id}",
            headers=auth_headers,
        )

        assert response.status_code == 404

    def test_pending_responses_lists_owned_items(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """Owned pending review responses should be listed."""
        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-pending-1",
            review_author="Customer",
            review_rating=5,
            review_text="Amazing service",
            review_date=datetime.now(UTC),
            ai_draft="Thank you for visiting us!",
            intent=ReviewIntent.PRAISE,
            tone="grateful",
            status=ResponseStatus.PENDING,
        )
        db.add(review_response)
        db.commit()

        response = client.get("/reviews/pending", headers=auth_headers)

        assert response.status_code == 200
        data = response.json()
        assert len(data) == 1
        assert data[0]["review_id"] == "review-pending-1"
        assert data[0]["status"] == "pending"
        assert data[0]["high_priority"] is False

    def test_pending_high_priority_filter(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """High priority pending responses should be filterable."""
        high_priority_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-pending-high-1",
            review_author="Urgent Customer",
            review_rating=1,
            review_text="Refund never came through",
            review_date=_naive_utc_now(),
            ai_draft="We are sorry about that.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.PENDING,
        )
        normal_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-pending-normal-1",
            review_author="Happy Customer",
            review_rating=5,
            review_text="Great experience",
            review_date=_naive_utc_now(),
            ai_draft="Thank you for the kind words!",
            intent=ReviewIntent.PRAISE,
            tone="grateful",
            status=ResponseStatus.PENDING,
        )
        db.add_all([high_priority_response, normal_response])
        db.commit()

        response = client.get(
            "/reviews/pending?high_priority_only=true",
            headers=auth_headers,
        )

        assert response.status_code == 200
        data = response.json()
        assert len(data) == 1
        assert data[0]["review_id"] == "review-pending-high-1"
        assert data[0]["high_priority"] is True
        assert data[0]["priority_level"] == "high"


class TestReviewResponderApproval:
    """Tests for approval and rejection flows."""

    def test_approve_response_forbidden_other_accounts_location(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        other_location,
        db: Session,
    ) -> None:
        """A user cannot approve another account's review response."""
        review_response = ReviewResponse(
            location_id=other_location.id,
            review_id="review-other-1",
            review_author="Other Customer",
            review_rating=4,
            review_text="Nice place",
            review_date=datetime.now(UTC),
            ai_draft="Thanks for your review!",
            intent=ReviewIntent.PRAISE,
            tone="warm",
            status=ResponseStatus.PENDING,
        )
        db.add(review_response)
        db.commit()

        response = client.post(
            f"/reviews/{review_response.id}/approve",
            headers=auth_headers,
            json={"response_id": review_response.id},
        )

        assert response.status_code == 404

    def test_approve_response_success(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Approving an owned response should update status and approver fields."""
        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-approve-1",
            review_author="Customer",
            review_rating=5,
            review_text="Perfect service",
            review_date=datetime.now(UTC),
            ai_draft="Thanks so much for your review!",
            intent=ReviewIntent.PRAISE,
            tone="grateful",
            status=ResponseStatus.PENDING,
        )
        db.add(review_response)
        db.commit()

        oauth_token = OAuthToken(
            account_id=test_user.id,
            location_id=test_location.id,
            provider=OAuthProvider.GOOGLE,
            access_token_ref="access-token",
            refresh_token_ref="refresh-token",
            expires_at=datetime.now(UTC),
            status=OAuthStatus.HEALTHY,
        )
        db.add(oauth_token)
        db.commit()

        class FakeGBP:
            async def reply_to_review(self, access_token: str, review_name: str, comment: str):
                assert access_token == "access-token"
                assert review_name == "review-approve-1"
                assert comment == "Edited draft"
                return {"name": "responses/123"}

        monkeypatch.setattr(
            "app.services.review_responder_service.get_google_api_service",
            lambda: FakeGBP(),
        )

        response = client.post(
            f"/reviews/{review_response.id}/approve",
            headers=auth_headers,
            json={"response_id": review_response.id, "edited_draft": "Edited draft"},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "published"
        assert data["approved_by"] == str(test_user.id)
        assert data["ai_draft"] == "Edited draft"
        assert data["platform_response_id"] == "responses/123"
        assert data["publish_error"] is None

    def test_approve_response_marks_failed_when_gbp_publish_unavailable(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Approving without GBP credentials should fail honestly."""
        async def fake_send_email(self, **kwargs):
            return {"success": True, "provider": "fake-email"}

        monkeypatch.setattr("app.services.notification.NotificationService.send_email", fake_send_email)

        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-approve-no-token",
            review_author="Customer",
            review_rating=5,
            review_text="Great service",
            review_date=datetime.now(UTC),
            ai_draft="Thanks for your review!",
            intent=ReviewIntent.PRAISE,
            tone="grateful",
            status=ResponseStatus.PENDING,
        )
        db.add(review_response)
        db.commit()

        response = client.post(
            f"/reviews/{review_response.id}/approve",
            headers=auth_headers,
            json={"response_id": review_response.id},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "failed"
        assert data["platform_response_id"] is None
        assert data["published_at"] is None
        assert "reconnect google" in data["publish_error"].lower()

        event = (
            db.query(NotificationEvent)
            .filter(
                NotificationEvent.account_id == test_location.account_id,
                NotificationEvent.type == "review_response_publish_failed",
            )
            .one()
        )
        assert "Review response publish failed" in event.title
        assert "reconnect google" in event.body.lower()
        assert event.url == "/dashboard/review-responder"

        delivery_log = (
            db.query(NotificationDeliveryLog)
            .filter(NotificationDeliveryLog.notification_event_id == event.id)
            .one()
        )
        assert delivery_log.delivery_status == "delivered"

    def test_reject_response_success(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
    ) -> None:
        """Rejecting an owned response should persist reason and approver."""
        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-reject-1",
            review_author="Customer",
            review_rating=2,
            review_text="Bad experience",
            review_date=datetime.now(UTC),
            ai_draft="We are sorry to hear that.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.PENDING,
        )
        db.add(review_response)
        db.commit()

        response = client.post(
            f"/reviews/{review_response.id}/reject",
            headers=auth_headers,
            json={"response_id": review_response.id, "reason": "Needs manual rewrite"},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "rejected"
        assert data["approved_by"] == str(test_user.id)
        assert data["rejection_reason"] == "Needs manual rewrite"


class TestReviewResponderRetry:
    """Tests for the retry publish endpoint."""

    def test_retry_failed_response_success(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Retrying a failed response with valid GBP credentials should publish it."""
        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-retry-success",
            review_author="Customer",
            review_rating=4,
            review_text="Good place",
            review_date=_naive_utc_now(),
            ai_draft="Thanks for visiting!",
            intent=ReviewIntent.PRAISE,
            tone="warm",
            status=ResponseStatus.FAILED,
            approved_by=test_user.id,
            approved_at=_naive_utc_now(),
            publish_error="GBP review publishing failed and needs operator attention: timeout",
        )
        db.add(review_response)
        db.commit()

        oauth_token = OAuthToken(
            account_id=test_user.id,
            location_id=test_location.id,
            provider=OAuthProvider.GOOGLE,
            access_token_ref="access-token-retry",
            refresh_token_ref="refresh-token-retry",
            expires_at=_naive_utc_now(),
            status=OAuthStatus.HEALTHY,
        )
        db.add(oauth_token)
        db.commit()

        class FakeGBP:
            async def reply_to_review(self, access_token: str, review_name: str, comment: str):
                return {"name": "responses/retry-1"}

        monkeypatch.setattr(
            "app.services.review_responder_service.get_google_api_service",
            lambda: FakeGBP(),
        )

        response = client.post(f"/reviews/{review_response.id}/retry", headers=auth_headers)

        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "published"
        assert data["publish_error"] is None
        assert data["platform_response_id"] == "responses/retry-1"

    def test_retry_failed_response_still_fails(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
    ) -> None:
        """Retrying without GBP credentials should keep status failed with updated error."""
        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-retry-fail",
            review_author="Customer",
            review_rating=3,
            review_text="Average experience",
            review_date=_naive_utc_now(),
            ai_draft="Thanks for your feedback!",
            intent=ReviewIntent.SUGGESTION,
            tone="empathetic",
            status=ResponseStatus.FAILED,
            approved_by=test_user.id,
            approved_at=_naive_utc_now(),
            publish_error="old error",
        )
        db.add(review_response)
        db.commit()

        response = client.post(f"/reviews/{review_response.id}/retry", headers=auth_headers)

        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "failed"
        assert data["publish_error"] is not None
        assert "reconnect google" in data["publish_error"].lower()
        assert data["platform_response_id"] is None
        assert data["published_at"] is None

    def test_retry_non_failed_response_returns_400(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """Retrying a pending response should return 400 — only failed is retryable."""
        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="review-retry-pending",
            review_author="Customer",
            review_rating=5,
            review_text="Great!",
            review_date=_naive_utc_now(),
            ai_draft="Thank you!",
            intent=ReviewIntent.PRAISE,
            tone="grateful",
            status=ResponseStatus.PENDING,
        )
        db.add(review_response)
        db.commit()

        response = client.post(f"/reviews/{review_response.id}/retry", headers=auth_headers)

        assert response.status_code == 400
        assert "only allowed for failed" in response.json()["detail"].lower()

    def test_retry_other_accounts_response_returns_404(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        other_location,
        db: Session,
    ) -> None:
        """Cannot retry another account's failed response."""
        review_response = ReviewResponse(
            location_id=other_location.id,
            review_id="review-retry-other",
            review_author="Customer",
            review_rating=2,
            review_text="Bad",
            review_date=_naive_utc_now(),
            ai_draft="Sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            publish_error="some error",
        )
        db.add(review_response)
        db.commit()

        response = client.post(f"/reviews/{review_response.id}/retry", headers=auth_headers)

        assert response.status_code == 404


class TestReviewResponderFailedView:
    """Tests for the dedicated failed-only operational view."""

    def test_failed_view_returns_only_failed_items(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """GET /reviews/failed must return only failed-status items."""
        records = [
            ReviewResponse(
                location_id=test_location.id,
                review_id="failed-view-failed-1",
                review_author="Alice",
                review_rating=2,
                review_text="Terrible service",
                review_date=_naive_utc_now(),
                ai_draft="We apologise.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.FAILED,
                publish_error=(
                    "GBP review publishing is unavailable because no Google OAuth token is connected."
                ),
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="failed-view-pending-1",
                review_author="Bob",
                review_rating=5,
                review_text="Great!",
                review_date=_naive_utc_now(),
                ai_draft="Thank you!",
                intent=ReviewIntent.PRAISE,
                tone="grateful",
                status=ResponseStatus.PENDING,
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="failed-view-published-1",
                review_author="Carol",
                review_rating=4,
                review_text="Nice place",
                review_date=_naive_utc_now(),
                ai_draft="Thanks for visiting!",
                intent=ReviewIntent.PRAISE,
                tone="warm",
                status=ResponseStatus.PUBLISHED,
                platform_response_id="resp-pub-1",
            ),
        ]
        db.add_all(records)
        db.commit()

        response = client.get("/reviews/failed", headers=auth_headers)

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 1
        assert len(data["items"]) == 1
        item = data["items"][0]
        assert item["review_id"] == "failed-view-failed-1"
        assert item["status"] == "failed"

    def test_failed_view_returns_error_category(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """Failed view items must carry an error_category and summary counts."""
        records = [
            ReviewResponse(
                location_id=test_location.id,
                review_id="failed-cat-oauth",
                review_author="Dave",
                review_rating=1,
                review_text="Bad",
                review_date=_naive_utc_now(),
                ai_draft="Sorry.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.FAILED,
                publish_error="no Google OAuth token is connected",
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="failed-cat-token",
                review_author="Eve",
                review_rating=2,
                review_text="Not great",
                review_date=_naive_utc_now(),
                ai_draft="We apologize.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.FAILED,
                publish_error="Google access token is missing",
            ),
        ]
        db.add_all(records)
        db.commit()

        response = client.get("/reviews/failed", headers=auth_headers)

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 2
        items_by_review_id = {item["review_id"]: item for item in data["items"]}
        assert items_by_review_id["failed-cat-oauth"]["error_category"] == "no_oauth_token"
        assert items_by_review_id["failed-cat-token"]["error_category"] == "token_missing"
        counts = data["error_category_counts"]
        assert counts.get("no_oauth_token") == 1
        assert counts.get("token_missing") == 1

    def test_failed_view_hides_other_accounts_location(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        other_location,
    ) -> None:
        """Passing another account's location_id must return 404."""
        response = client.get(
            f"/reviews/failed?location_id={other_location.id}",
            headers=auth_headers,
        )
        assert response.status_code == 404

    def test_failed_view_search_filter(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """Search should narrow results within the failed view."""
        records = [
            ReviewResponse(
                location_id=test_location.id,
                review_id="failed-search-match",
                review_author="Frank",
                review_rating=1,
                review_text="The refund never arrived",
                review_date=_naive_utc_now(),
                ai_draft="We are sorry.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.FAILED,
                publish_error="api error",
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="failed-search-nomatch",
                review_author="Grace",
                review_rating=2,
                review_text="Staff was rude",
                review_date=_naive_utc_now(),
                ai_draft="We apologize.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.FAILED,
                publish_error="api error",
            ),
        ]
        db.add_all(records)
        db.commit()

        response = client.get("/reviews/failed?search=refund", headers=auth_headers)

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 1
        assert data["items"][0]["review_id"] == "failed-search-match"

    def test_failed_view_publish_error_is_surfaced(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """publish_error must be non-null and present in the failed item payload."""
        rr = ReviewResponse(
            location_id=test_location.id,
            review_id="failed-error-surface",
            review_author="Harry",
            review_rating=1,
            review_text="Nothing worked",
            review_date=_naive_utc_now(),
            ai_draft="We are deeply sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            publish_error="GBP review publishing failed and needs operator attention: timeout",
        )
        db.add(rr)
        db.commit()

        response = client.get("/reviews/failed", headers=auth_headers)

        assert response.status_code == 200
        item = response.json()["items"][0]
        assert item["publish_error"] is not None
        assert "timeout" in item["publish_error"]


class TestReviewResponderBulkRetry:
    """Tests for the bulk retry endpoint."""

    def test_bulk_retry_all_succeed(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """All owned failed items retried with valid GBP should be published."""
        records = [
            ReviewResponse(
                location_id=test_location.id,
                review_id=f"bulk-retry-ok-{i}",
                review_author="Customer",
                review_rating=3,
                review_text="Average",
                review_date=_naive_utc_now(),
                ai_draft="Thanks for the feedback!",
                intent=ReviewIntent.SUGGESTION,
                tone="empathetic",
                status=ResponseStatus.FAILED,
                approved_by=test_user.id,
                approved_at=_naive_utc_now(),
                publish_error="old error",
            )
            for i in range(3)
        ]
        db.add_all(records)
        db.commit()

        oauth_token = OAuthToken(
            account_id=test_user.id,
            location_id=test_location.id,
            provider=OAuthProvider.GOOGLE,
            access_token_ref="bulk-token",
            refresh_token_ref="bulk-refresh",
            expires_at=_naive_utc_now(),
            status=OAuthStatus.HEALTHY,
        )
        db.add(oauth_token)
        db.commit()

        call_count = {"n": 0}

        class FakeGBP:
            async def reply_to_review(self, access_token: str, review_name: str, comment: str):
                call_count["n"] += 1
                return {"name": f"responses/bulk-{call_count['n']}"}

        monkeypatch.setattr(
            "app.services.review_responder_service.get_google_api_service",
            lambda: FakeGBP(),
        )

        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": [rr.id for rr in records]},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 3
        assert data["succeeded"] == 3
        assert data["still_failed"] == 0
        assert data["skipped"] == 0
        assert all(r["success"] for r in data["results"])
        assert all(r["status"] == "published" for r in data["results"])

    def test_bulk_retry_without_gbp_keeps_failed(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
    ) -> None:
        """Bulk retrying without GBP credentials should report still_failed."""
        rr = ReviewResponse(
            location_id=test_location.id,
            review_id="bulk-retry-no-token",
            review_author="Customer",
            review_rating=2,
            review_text="Bad",
            review_date=_naive_utc_now(),
            ai_draft="Sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            approved_by=test_user.id,
            approved_at=_naive_utc_now(),
            publish_error="old error",
        )
        db.add(rr)
        db.commit()

        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": [rr.id]},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["still_failed"] == 1
        assert data["succeeded"] == 0
        result = data["results"][0]
        assert result["success"] is False
        assert result["publish_error"] is not None
        assert "reconnect google" in result["publish_error"].lower()

    def test_bulk_retry_skips_other_accounts_items(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        other_location,
        db: Session,
    ) -> None:
        """Items belonging to another account must be silently skipped."""
        rr = ReviewResponse(
            location_id=other_location.id,
            review_id="bulk-retry-other-owner",
            review_author="Customer",
            review_rating=1,
            review_text="Awful",
            review_date=_naive_utc_now(),
            ai_draft="Sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            publish_error="old error",
        )
        db.add(rr)
        db.commit()

        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": [rr.id]},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["skipped"] == 1
        assert data["succeeded"] == 0
        assert data["still_failed"] == 0
        assert data["results"] == []

    def test_bulk_retry_skips_non_failed_items(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """Non-failed items in the request must be silently skipped."""
        pending = ReviewResponse(
            location_id=test_location.id,
            review_id="bulk-retry-pending-skip",
            review_author="Customer",
            review_rating=5,
            review_text="Great!",
            review_date=_naive_utc_now(),
            ai_draft="Thank you!",
            intent=ReviewIntent.PRAISE,
            tone="grateful",
            status=ResponseStatus.PENDING,
        )
        db.add(pending)
        db.commit()

        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": [pending.id]},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["skipped"] == 1
        assert data["succeeded"] == 0
        assert data["still_failed"] == 0

    def test_bulk_retry_mixed_owned_and_foreign(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        other_location,
        db: Session,
    ) -> None:
        """Mixed owned/foreign IDs: owned retried, foreign skipped."""
        owned = ReviewResponse(
            location_id=test_location.id,
            review_id="bulk-mixed-owned",
            review_author="Customer",
            review_rating=2,
            review_text="Bad",
            review_date=_naive_utc_now(),
            ai_draft="Sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            approved_by=test_user.id,
            approved_at=_naive_utc_now(),
            publish_error="old",
        )
        foreign = ReviewResponse(
            location_id=other_location.id,
            review_id="bulk-mixed-foreign",
            review_author="Customer",
            review_rating=1,
            review_text="Awful",
            review_date=_naive_utc_now(),
            ai_draft="Sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            publish_error="old",
        )
        db.add_all([owned, foreign])
        db.commit()

        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": [owned.id, foreign.id]},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 2
        assert data["skipped"] == 1
        # owned item attempted (no token → still_failed)
        assert data["still_failed"] == 1
        assert data["succeeded"] == 0

    def test_bulk_retry_empty_list_returns_400(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
    ) -> None:
        """Submitting an empty response_ids list must return 422 (validation)."""
        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": []},
        )
        assert response.status_code == 422


class TestReviewResponderHistory:
    """Tests for history, summary, and export views."""

    def test_review_summary_returns_operator_totals(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """Summary should expose counts and activity timestamps."""
        records = [
            ReviewResponse(
                location_id=test_location.id,
                review_id="summary-pending-high",
                review_author="Urgent Customer",
                review_rating=1,
                review_text="Refund never came through",
                review_date=_naive_utc_now(),
                ai_draft="We are sorry about that.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.PENDING,
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="summary-published",
                review_author="Happy Customer",
                review_rating=5,
                review_text="Amazing support",
                review_date=_naive_utc_now(),
                ai_draft="Thanks so much!",
                intent=ReviewIntent.PRAISE,
                tone="grateful",
                status=ResponseStatus.PUBLISHED,
                approved_at=_naive_utc_now(),
                published_at=_naive_utc_now(),
                platform_response_id="resp-123",
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="summary-failed-high",
                review_author="Concerned Customer",
                review_rating=2,
                review_text="Need a refund and a fix",
                review_date=_naive_utc_now(),
                ai_draft="We will help resolve this.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.FAILED,
                approved_at=_naive_utc_now(),
            ),
        ]
        db.add_all(records)
        db.commit()

        response = client.get(
            f"/reviews/summary?location_id={test_location.id}",
            headers=auth_headers,
        )

        assert response.status_code == 200
        data = response.json()
        assert data["total_count"] == 3
        assert data["pending_count"] == 1
        assert data["published_count"] == 1
        assert data["failed_count"] == 1
        assert data["high_priority_pending_count"] == 1
        assert data["high_priority_total_count"] == 2
        assert data["average_rating"] == 2.7
        assert data["last_activity_at"] is not None
        assert data["last_failed_at"] is not None
        assert data["last_published_at"] is not None

    def test_review_history_filters_search_and_priorities(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """History should support search, filters, and priority visibility."""
        records = [
            ReviewResponse(
                location_id=test_location.id,
                review_id="history-normal",
                review_author="Taylor",
                review_rating=5,
                review_text="Great service and fast reply",
                review_date=_naive_utc_now(),
                ai_draft="Thank you!",
                intent=ReviewIntent.PRAISE,
                tone="grateful",
                status=ResponseStatus.PUBLISHED,
                approved_at=_naive_utc_now(),
                published_at=_naive_utc_now(),
                platform_response_id="resp-1",
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="history-high",
                review_author="Jamie",
                review_rating=1,
                review_text="Refund still missing and nobody called me back",
                review_date=_naive_utc_now(),
                ai_draft="We are sorry for the delay.",
                intent=ReviewIntent.COMPLAINT,
                tone="apologetic",
                status=ResponseStatus.FAILED,
                approved_at=_naive_utc_now(),
                rejection_reason="Needs manual rewrite",
            ),
            ReviewResponse(
                location_id=test_location.id,
                review_id="history-question",
                review_author="Morgan",
                review_rating=3,
                review_text="Do you take walk-ins?",
                review_date=_naive_utc_now(),
                ai_draft="Yes, we do.",
                intent=ReviewIntent.QUESTION,
                tone="empathetic",
                status=ResponseStatus.PENDING,
            ),
        ]
        db.add_all(records)
        db.commit()

        response = client.get(
            "/reviews/history?status_filter=failed&high_priority_only=true&search=refund&limit=5&offset=0",
            headers=auth_headers,
        )

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 1
        assert data["limit"] == 5
        assert data["offset"] == 0
        assert len(data["items"]) == 1
        item = data["items"][0]
        assert item["review_id"] == "history-high"
        assert item["high_priority"] is True
        assert item["priority_level"] == "high"
        assert item["priority_reason"]
        assert item["age_minutes"] is not None

    def test_review_history_export_returns_csv(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """History export should return CSV with operator metadata."""
        review_response = ReviewResponse(
            location_id=test_location.id,
            review_id="history-export-1",
            review_author="Export Customer",
            review_rating=2,
            review_text="Need a refund now",
            review_date=_naive_utc_now(),
            ai_draft="We are sorry to hear that.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            approved_at=_naive_utc_now(),
            rejection_reason="Manual rewrite needed",
        )
        db.add(review_response)
        db.commit()

        response = client.get(
            "/reviews/history/export?high_priority_only=true&search=refund",
            headers=auth_headers,
        )

        assert response.status_code == 200
        assert "text/csv" in response.headers["content-type"]
        assert "attachment; filename=\"review-responder-history.csv\"" in response.headers[
            "content-disposition"
        ]
        body = response.text
        assert "history-export-1" in body
        assert "priority_level" in body
        assert "high_priority" in body
        assert "publish_error" in body


class TestBulkRetryLogPersistence:
    """Tests for BulkRetryLog persistence and summary exposure."""

    def test_bulk_retry_persists_log(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
        monkeypatch,
    ) -> None:
        """Bulk retry must write a BulkRetryLog row for the account."""
        rr = ReviewResponse(
            location_id=test_location.id,
            review_id="log-persist-1",
            review_author="Customer",
            review_rating=2,
            review_text="Bad",
            review_date=_naive_utc_now(),
            ai_draft="Sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            approved_by=test_user.id,
            approved_at=_naive_utc_now(),
            publish_error="old error",
        )
        db.add(rr)
        db.commit()

        oauth_token = OAuthToken(
            account_id=test_user.id,
            location_id=test_location.id,
            provider=OAuthProvider.GOOGLE,
            access_token_ref="persist-token",
            refresh_token_ref="persist-refresh",
            expires_at=_naive_utc_now(),
            status=OAuthStatus.HEALTHY,
        )
        db.add(oauth_token)
        db.commit()

        class FakeGBP:
            async def reply_to_review(self, access_token: str, review_name: str, comment: str):
                return {"name": "responses/log-1"}

        monkeypatch.setattr(
            "app.services.review_responder_service.get_google_api_service",
            lambda: FakeGBP(),
        )

        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": [rr.id]},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["succeeded"] == 1

        # Verify the log row was written
        log = (
            db.query(BulkRetryLog)
            .filter(BulkRetryLog.account_id == test_user.id)
            .order_by(BulkRetryLog.created_at.desc())
            .first()
        )
        assert log is not None
        assert log.succeeded == 1
        assert log.still_failed == 0
        assert log.total == 1
        assert log.skipped == 0

    def test_bulk_retry_log_persisted_for_still_failed(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
    ) -> None:
        """A bulk retry that keeps items failed still writes a log row."""
        rr = ReviewResponse(
            location_id=test_location.id,
            review_id="log-still-failed-1",
            review_author="Customer",
            review_rating=1,
            review_text="Awful",
            review_date=_naive_utc_now(),
            ai_draft="Sorry.",
            intent=ReviewIntent.COMPLAINT,
            tone="apologetic",
            status=ResponseStatus.FAILED,
            approved_by=test_user.id,
            approved_at=_naive_utc_now(),
            publish_error="no token",
        )
        db.add(rr)
        db.commit()

        response = client.post(
            "/reviews/bulk-retry",
            headers=auth_headers,
            json={"response_ids": [rr.id]},
        )

        assert response.status_code == 200
        data = response.json()
        assert data["still_failed"] == 1

        log = (
            db.query(BulkRetryLog)
            .filter(BulkRetryLog.account_id == test_user.id)
            .order_by(BulkRetryLog.created_at.desc())
            .first()
        )
        assert log is not None
        assert log.still_failed == 1
        assert log.succeeded == 0

    def test_summary_exposes_last_bulk_retry_fields(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
    ) -> None:
        """GET /reviews/summary must include bulk retry stats from the latest log."""
        # Seed a log row directly (simulates a prior bulk retry)
        log = BulkRetryLog(
            account_id=test_user.id,
            total=5,
            succeeded=3,
            still_failed=2,
            skipped=0,
        )
        db.add(log)
        db.commit()

        response = client.get(
            f"/reviews/summary?location_id={test_location.id}",
            headers=auth_headers,
        )

        assert response.status_code == 200
        data = response.json()
        assert data["last_bulk_retry_at"] is not None
        assert data["last_bulk_retry_succeeded"] == 3
        assert data["last_bulk_retry_still_failed"] == 2
        assert data["last_bulk_retry_total"] == 5

    def test_summary_bulk_retry_fields_null_when_no_log(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_location,
        db: Session,
    ) -> None:
        """Summary bulk retry fields must be null when no log exists for the account."""
        response = client.get(
            f"/reviews/summary?location_id={test_location.id}",
            headers=auth_headers,
        )

        assert response.status_code == 200
        data = response.json()
        assert data["last_bulk_retry_at"] is None
        assert data["last_bulk_retry_succeeded"] is None
        assert data["last_bulk_retry_still_failed"] is None
        assert data["last_bulk_retry_total"] is None

    def test_summary_returns_most_recent_bulk_retry_log(
        self,
        client: TestClient,
        auth_headers: dict[str, str],
        test_user,
        test_location,
        db: Session,
    ) -> None:
        """Summary should reflect the most recent log row, not an older one."""
        older_log = BulkRetryLog(
            account_id=test_user.id,
            total=10,
            succeeded=2,
            still_failed=8,
            skipped=0,
            created_at=datetime(2026, 1, 1, 12, 0, 0),
        )
        newer_log = BulkRetryLog(
            account_id=test_user.id,
            total=3,
            succeeded=3,
            still_failed=0,
            skipped=0,
            created_at=datetime(2026, 2, 1, 12, 0, 0),
        )
        db.add_all([older_log, newer_log])
        db.commit()

        response = client.get(
            f"/reviews/summary?location_id={test_location.id}",
            headers=auth_headers,
        )

        assert response.status_code == 200
        data = response.json()
        # Should reflect the newer log (succeeded=3, not 2)
        assert data["last_bulk_retry_succeeded"] == 3
        assert data["last_bulk_retry_still_failed"] == 0
        assert data["last_bulk_retry_total"] == 3
