"""AI compliance and legal disclaimer utilities."""

from typing import Any


class AIComplianceManager:
    """Manager for AI-generated content compliance and disclaimers."""

    # Standard AI disclaimer text
    AI_DISCLAIMER = "Generated by AI - Subject to human review"
    AI_DISCLAIMER_FULL = (
        "This content was generated by artificial intelligence and should be "
        "reviewed by a human before publication. The business owner is responsible "
        "for the accuracy and appropriateness of all published content."
    )

    @staticmethod
    def add_disclaimer_to_text(text: str, full: bool = False) -> str:
        """
        Add AI disclaimer to text content.

        Args:
            text: Original text
            full: Whether to use full disclaimer

        Returns:
            Text with disclaimer appended
        """
        disclaimer = (
            AIComplianceManager.AI_DISCLAIMER_FULL
            if full
            else AIComplianceManager.AI_DISCLAIMER
        )
        return f"{text}\n\n{disclaimer}"

    @staticmethod
    def add_disclaimer_metadata(data: dict[str, Any]) -> dict[str, Any]:
        """
        Add AI disclaimer to metadata dictionary.

        Args:
            data: Original data dictionary

        Returns:
            Data with disclaimer metadata
        """
        data["ai_generated"] = True
        data["ai_disclaimer"] = AIComplianceManager.AI_DISCLAIMER
        data["requires_human_review"] = True
        return data

    @staticmethod
    def get_terms_text() -> str:
        """
        Get AI-related terms and conditions text.

        Returns:
            Terms text for user agreements
        """
        return """
AI-GENERATED CONTENT TERMS

1. AI Content Generation
   This service uses artificial intelligence to generate content including text, 
   images, and recommendations. All AI-generated content is provided as suggestions 
   and drafts only.

2. Human Review Required
   You acknowledge that all AI-generated content must be reviewed, edited, and 
   approved by you before publication. You are solely responsible for ensuring 
   the accuracy, appropriateness, and compliance of all published content.

3. Content Responsibility
   The final responsibility for all content published through this service rests 
   with you, the business owner. This includes but is not limited to:
   - Review responses
   - Social media posts
   - Marketing materials
   - Customer communications

4. No Liability for AI Errors
   We are not liable for any errors, inaccuracies, or inappropriate content 
   generated by AI systems. You must verify all AI-generated content before use.

5. Compliance with Platform Policies
   You are responsible for ensuring all published content complies with the 
   terms of service and community guidelines of third-party platforms 
   (Google, Facebook, Instagram, etc.).

6. Data Usage
   AI systems may analyze your business data, reviews, and other information 
   to generate personalized content. This data is used solely for service 
   delivery and is not shared with third parties.

By using this service, you agree to these terms and accept full responsibility 
for all content published through or with the assistance of this platform.
"""

    @staticmethod
    def get_onboarding_consent_text() -> str:
        """
        Get consent text for onboarding flow.

        Returns:
            Consent text for user acceptance
        """
        return """
I understand and agree that:

✓ AI-generated content is provided as suggestions only
✓ I must review and approve all content before publication
✓ I am responsible for the accuracy and appropriateness of all published content
✓ The service provider is not liable for AI-generated content errors
✓ I will comply with all third-party platform policies and guidelines
"""

    @staticmethod
    def validate_content_for_publication(content: str) -> tuple[bool, list[str]]:
        """
        Validate content before publication (basic checks).

        Args:
            content: Content to validate

        Returns:
            Tuple of (is_valid, list of warnings)
        """
        warnings = []

        # Check for minimum length
        if len(content.strip()) < 10:
            warnings.append("Content is too short")

        # Check for placeholder text
        placeholders = ["[INSERT", "TODO", "PLACEHOLDER", "XXX"]
        for placeholder in placeholders:
            if placeholder.lower() in content.lower():
                warnings.append(f"Content contains placeholder: {placeholder}")

        # Check for potentially problematic content
        sensitive_terms = [
            "guaranteed",
            "100%",
            "miracle",
            "cure",
            "medical advice",
        ]
        for term in sensitive_terms:
            if term.lower() in content.lower():
                warnings.append(f"Content contains sensitive term: {term}")

        is_valid = len(warnings) == 0
        return is_valid, warnings
